### ISSUE TITLE
ES Module Support

### ISSUE THREAD

**Issue by danielsigl** [scaranaraa/wordcloud-generator#1]
Hello @scaranaraa and thank you for this project!

Would it be possible to kindly add ES Module support to implement with require()?

Error [ERR_REQUIRE_ESM]: require() of ES Module

Thanks in Advance!

Best regards,
Daniel

**Comment by duckyies** [comment]
Hey! I'll look into adding require() support soon.

**Comment by duckyies** [comment]
You should now be able to use require() with the latest npm release!
