### ISSUE TITLE
Error Missing Puppeteer Config

### ISSUE THREAD

**Issue by danielsigl** [scaranaraa/wordcloud-generator#2]
Hi @scaranaraa, thank you very much for making it possible to work with require! I'm getting this error now case there is no puppeteer config set. Can you implement setting the config that we do not have to add it in our code? Thanks in Advance!

`const WordCloud = require("wordcloud-generator");
 await WordCloud.generate(words, true, tempFilePath);
`

`DEFAULT 2024-06-01T20:47:05.678128Z [resource.labels.functionName: reportsScheduler] [labels.executionId: wvndb60mf0zj] Error: Could not find Chrome (ver. 125.0.6422.78). This can occur if either
DEFAULT 2024-06-01T20:47:05.678138Z [resource.labels.functionName: reportsScheduler] [labels.executionId: wvndb60mf0zj] 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
DEFAULT 2024-06-01T20:47:05.678142Z [resource.labels.functionName: reportsScheduler] [labels.executionId: wvndb60mf0zj] 2. your cache path is incorrectly configured (which is: /root/.cache/puppeteer).
DEFAULT 2024-06-01T20:47:05.678146Z [resource.labels.functionName: reportsScheduler] [labels.executionId: wvndb60mf0zj] For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
DEFAULT 2024-06-01T20:47:05.678151Z [resource.labels.functionName: reportsScheduler] [labels.executionId: wvndb60mf0zj] at ChromeLauncher.resolveExecutablePath (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:295:27)
DEFAULT 2024-06-01T20:47:05.678154Z [resource.labels.functionName: reportsScheduler] [labels.executionId: wvndb60mf0zj] at ChromeLauncher.executablePath (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:209:25)
DEFAULT 2024-06-01T20:47:05.678157Z [resource.labels.functionName: reportsScheduler] [labels.executionId: wvndb60mf0zj] at ChromeLauncher.computeLaunchArguments (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:89:37)
DEFAULT 2024-06-01T20:47:05.678160Z [resource.labels.functionName: reportsScheduler] [labels.executionId: wvndb60mf0zj] at async ChromeLauncher.launch (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:70:28)
DEFAULT 2024-06-01T20:47:05.678162Z [resource.labels.functionName: reportsScheduler] [labels.executionId: wvndb60mf0zj] at async Object.generate (/workspace/node_modules/wordcloud-generator/dist/generate.cjs:113:21)
DEFAULT 2024-06-01T20:47:05.678165Z [resource.labels.functionName: reportsScheduler] [labels.executionId: wvndb60mf0zj] at async generateWordCloudChartImage (/workspace/shoptimizer-manager/reports-scheduler.js:794:3)
`

**Comment by duckyies** [comment]
you can now set the puppeteer path under options

```js
await generate(words, true, undefined , {puppeteerPath: '/path/to/chromium'})
```
if it still throws that error, make sure chromium is installed correctly and try reinstalling this package
